### ISSUE TITLE
Feature Request: Use JWT token as authorization instead of user_id

### ISSUE THREAD

**Issue by zero734kr** [Saebasol/Heliotrope_deprecated#117]
user_id's can be easily used by unauthorized users, just by copying their user_id looking for issues in this repository.

How about using a third party service with Discord Oauth to verify that the user_id service provided by oauth is the same as the authorized user_id and, if so, print on the website's JWT token?

Or if you want it easier to implement, send the JWT token via the authorized user's DM.

**Comment by SaidBySolo** [comment]
Release in 3.3.1
